In [1]:
#create 3*3 numpy array with all zeros 
import numpy as np
arr1= np.zeros ((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
arr1=np.ones((2,2))
print(arr1)

[[1. 1.]
 [1. 1.]]


In [5]:
#create a 3*3 numpy array with random values between 0 and 1
arr3=np.random.rand(3,3)
print(arr3)

[[0.05649742 0.80845933 0.60184454]
 [0.9746455  0.26670857 0.86760454]
 [0.88738406 0.01776945 0.87367773]]


In [6]:
#create a numpy 10 equally spaced values 
arr4=np.linspace(0,1,10)
print(arr4)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [9]:
#create a 2*2 numpy arrays with diagonal values of 1 and off diagonal of 0
arr5=np.eye(3)
print(arr5)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#create a numpy array with 20 random integers between 1 and 100
arr6=np.random.randint(1,100,20)
print(arr6)

[54 15 63 48 74 40 20 62 58 75 28 17 65 88 64 56 80 61 34 11]


In [14]:
import numpy as np
arr7=np.arange(1,11)
even=arr7[arr7 % 2==0]
print(even)


[ 2  4  6  8 10]


In [16]:
arr8=np.array([[1,2,3],[4,5,6],[7,8,9]])
diagonal=np.diag(arr8)
print(diagonal)



TypeError: diag() takes from 1 to 2 positional arguments but 3 were given