# Import necesary libraries

In [1]:
import pandas as pd
import numpy as np

# Creates two DataFrames, d1 and d2, with different sets of data.

# In d1, there are two columns: "key" and "num1". The "key" column contains the values "a", "b", "c", "c", "d", and "e", while the "num1" column contains the numbers 0 to 5.

# In d2, there are two columns: "key" and "num2". The "key" column contains the values "b", "c", "e", and "f", while the "num2" column contains the numbers 0 to 3.

In [3]:
d1 = pd.DataFrame({"key": ["a", "b", "c", "c", 'd', 'e'],
                 "num1" :range(6)})
d2=pd.DataFrame(
 {"key":["b","c","e","f"],
 "num2":range(4)})
print(d1)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   c     3
4   d     4
5   e     5
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


# Perform a merge operation between the DataFrames d1 and d2.

In [4]:
pd.merge(d1,d2)

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

# Performs a merge operation between the DataFrames d1 and d2, specifically on the column 'key'.

In [5]:
pd.merge(d1 ,d2, on="key")

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

# Creates two DataFrames, d3 and d4, with different sets of data.

# In d3, there are two columns: "key1" and "num1". The "key1" column contains the values "a", "b", "c", "c", "d", and "e", while the "num1" column contains the numbers 0 to 5.

# In d4, there are two columns: "key2" and "num2". The "key2" column contains the values "b", "c", "e", and "f", while the "num2" column contains the numbers 0 to 3.

In [6]:
d3=pd.DataFrame(
 {"key1":["a","b","c","c","d","e"],
 "num1":range(6)})
d4=pd.DataFrame(
 {"key2":["b","c","e","f"],
 "num2":range(4)})
print(d3)
print(d4)

  key1  num1
0    a     0
1    b     1
2    c     2
3    c     3
4    d     4
5    e     5
  key2  num2
0    b     0
1    c     1
2    e     2
3    f     3


# Perform a merge operation between the DataFrames d3 and d4 based on different columns. (i.e. the merge operation should matche the values in the "key1" column of d3 with the values in the "key2" column of d4.)

In [7]:
pd.merge(d3,d4, left_on= "key1", right_on="key2")

key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    c     3    c     1
3    e     5    e     2

# Perform an outer join merge operation between the DataFrames d1 and d2.

In [9]:
pd.merge(d1, d2, how="outer")

key  num1  num2
0   a   0.0   NaN
1   b   1.0   0.0
2   c   2.0   1.0
3   c   3.0   1.0
4   d   4.0   NaN
5   e   5.0   2.0
6   f   NaN   3.0

# Perform an left join merge operation between the DataFrames d1 and d2.

In [10]:
pd.merge(d1,d2, how="left")

key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   c     3   1.0
4   d     4   NaN
5   e     5   2.0

# Perform an right join merge operation between the DataFrames d1 and d2.

In [11]:
pd.merge(d1, d2, how="right")

key  num1  num2
0   b   1.0     0
1   c   2.0     1
2   c   3.0     1
3   e   5.0     2
4   f   NaN     3

# Perform an inner join merge operation between the DataFrames d1 and d2.

In [13]:
pd.merge(d1,d2, how="inner")

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

# Create two DataFrames, df1 and df2, with different sets of data.

# In df1, there are three columns: "key", "num1", and "count". The "key" column contains the values "a", "b", "c", "c", "d", and "e". The "num1" column contains the numbers 0 to 5, and the "count" column contains the values "one", "three", "two", "one", "one", and "two".

# In df2, there are three columns: "key", "num2", and "count". The "key" column contains the values "b", "c", "e", and "f". The "num2" column contains the numbers 0 to 3, and the "count" column contains the values "one", "two", "two", and "two".

In [15]:
right=pd.DataFrame(
 [[1,2],[3,4],[5,6]],
 index=["a","c","d"],
 columns=["Tom","Tim"])

left=pd.DataFrame(
 [[7,8],[9,10],[11,12],[13,14]],
 index=["a","b","e","f"],
 columns=["Sam","Kim"])

print(right)
print(left)

   Tom  Tim
a    1    2
c    3    4
d    5    6
   Sam  Kim
a    7    8
b    9   10
e   11   12
f   13   14


# Perform an outer join merge operation between two DataFrames, right and left, based on their index values.

In [16]:
pd.merge(right, left, 
        right_index = True,
        left_index = True,
        how="outer")

Tom  Tim   Sam   Kim
a  1.0  2.0   7.0   8.0
b  NaN  NaN   9.0  10.0
c  3.0  4.0   NaN   NaN
d  5.0  6.0   NaN   NaN
e  NaN  NaN  11.0  12.0
f  NaN  NaN  13.0  14.0

# Performs a join operation between two DataFrames, left and right, using their index values.

In [18]:
left.join(right)

Sam  Kim  Tom  Tim
a    7    8  1.0  2.0
b    9   10  NaN  NaN
e   11   12  NaN  NaN
f   13   14  NaN  NaN

# Perform an outer join operation between two DataFrames, left and right, using their index values.

In [19]:
left.join(right , how="outer")

Sam   Kim  Tom  Tim
a   7.0   8.0  1.0  2.0
b   9.0  10.0  NaN  NaN
c   NaN   NaN  3.0  4.0
d   NaN   NaN  5.0  6.0
e  11.0  12.0  NaN  NaN
f  13.0  14.0  NaN  NaN

# Task 

# Create a DataFrame called data 
# The DataFrame has three rows labeled as "a", "b", and "f", and two columns labeled as "Alex" and "Keta".

In [22]:
data=pd.DataFrame([[1,3],[5,7],[9,11]],
 index=["a","b","f"],
 columns=["Alex","Keta"])
data

Alex  Keta
a     1     3
b     5     7
f     9    11

# Perform a join operation between multiple DataFrames, including left, right, and data.

In [24]:
left.join([right,data])

Sam   Kim  Tom  Tim  Alex  Keta
a   7.0   8.0  1.0  2.0   1.0   3.0
b   9.0  10.0  NaN  NaN   5.0   7.0
e  11.0  12.0  NaN  NaN   NaN   NaN
f  13.0  14.0  NaN  NaN   9.0  11.0

# Concatenating Along an Axis

# Ccreate a NumPy array called seq with a shape of (4, 5).

In [25]:
seq= np.arange(20).reshape(4,5)
seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Perform a concatenation operation on the NumPy array seq

In [26]:
np.concatenate([seq, seq] , axis = 0) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Perform a concatenation operation on the NumPy array seq

In [27]:
np.concatenate([seq, seq] , axis = 1) 

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

# Create three pandas Series objects named data1, data2, and data3, each with different values and associated index labels.

# In data1, the Series contains the values 0 and 1, with index labels 'a' and 'b' respectively.

# In data2, the Series contains the values 2, 3, and 4, with index labels 'c', 'd', and 'e' respectively.

# In data3, the Series contains the values 5 and 6, with index labels 'f' and 'g' respectively.

In [28]:
data1 = pd.Series(
 [0, 1], index=['a', 'b'])
data2 = pd.Series(
 [2,3,4], index=['c','d','e'])
data3 = pd.Series(
 [5, 6], index=['f', 'g'])
print(data1)
print(data2)
print(data3)

a    0
b    1
dtype: int64
c    2
d    3
e    4
dtype: int64
f    5
g    6
dtype: int64


# Perform a concatenation operation on the pandas Series objects data1, data2, and data3.

In [29]:
pd.concat([data1,data2,data3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

# Perform a concatenation operation on the pandas Series objects data1, data2, and data3 along the horizontal axis (axis=1).

In [30]:
pd.concat([data1,data2,data3], axis = 1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

# Create a pandas Series called data4 with values [10, 11, 12] and index labels ['a', 'b', 'c']. Perform a concatenation operation on the pandas Series objects data1 and data4 along the horizontal axis (axis=1) using the "inner" join.

In [32]:
data4= pd.Series([10,11,12],
 index=['a','b',"c"])
pd.concat([data1, data4], axis = 1, join="inner")

0   1
a  0  10
b  1  11

# Perform a concatenation operation on the pandas Series objects data1, data2, and data4 and assign the result to the variable x. Use The keys parameter to assign labels to the concatenated Series.

In [35]:
x = pd.concat([data1, data2, data4] , keys = ['one', 'two', 'three'])
x

one    a     0
       b     1
two    c     2
       d     3
       e     4
three  a    10
       b    11
       c    12
dtype: int64

# Task 

# Create two pandas DataFrames, data1 and data2, with randomly generated data.

# The data1 DataFrame is created using the pd.DataFrame() function and a 3x4 NumPy array of random numbers generated by np.random.randn(3, 4). The columns of data1 are labeled as 'a', 'b', 'c', and 'd'.

# The data2 DataFrame is created in a similar way, but with a 2x3 NumPy array of random numbers generated by np.random.randn(2, 3). The columns of data2 are labeled as 'b', 'd', and 'a'.



In [36]:
data1 = pd.DataFrame(
 np.random.randn(3, 4),
 columns=['a','b','c','d'])
data2 = pd.DataFrame(
 np.random.randn(2, 3),
 columns=['b','d','a'])
print(data1)
print(data2)

          a         b         c         d
0 -0.300429  0.765859  0.749039  0.693156
1  1.719054 -0.139805 -0.255436  0.249724
2  1.788607 -1.196014 -0.219635 -1.403504
          b         d         a
0  0.689129  0.502160  0.955935
1  0.310184 -1.716892 -0.098959


# Perform a concatenation operation on the pandas DataFrames data1 and data2 and combine them into a single DataFrame. 

In [37]:
pd.concat([data1, data2])

a         b         c         d
0 -0.300429  0.765859  0.749039  0.693156
1  1.719054 -0.139805 -0.255436  0.249724
2  1.788607 -1.196014 -0.219635 -1.403504
0  0.955935  0.689129       NaN  0.502160
1 -0.098959  0.310184       NaN -1.716892